### ISSUE TITLE
specify full volume paths

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/bank-of-anthos#114]
this isn't quite a best practice

```
      volumes:
      - name: keys
        secret:
          secretName: jwt-key
          items:
          - key: jwtRS256.key
            path: privatekey
          - key: jwtRS256.key.pub
            path: publickey
```

since the relative path e.g. /root/ can change based on user set in dockerfile
or at execution time (as a matter of fact, disabling root execution is a very
common GKE/kubernetes best practice).

Please use paths like /etc/secrets/foo etc.
