### ISSUE TITLE
Consider removing jwt-secret from skaffold

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/bank-of-anthos#125]
```
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
    # deploy a pre-build secret
    # in practice, this should not be checked in to source control
    - ./extras/jwt/jwt-secret.yaml
```

due to the last line, skaffold iterations (run + delete) are overwriting and
deleting the secret generated via

    openssl genrsa -out jwtRS256.key 4096
    openssl rsa -in jwtRS256.key -outform PEM -pubout -out jwtRS256.key.pub
    kubectl create secret generic jwt-key --from-file=./jwtRS256.key --from-file=./jwtRS256.key.pub

in the README.md. I think checking in the secret isn't such a bad idea and
since it doesn't provide actual security to this project, it helps people get
thinks get up and running much easier.
