### ISSUE TITLE
offer instructions for on-prem clusters

### ISSUE THREAD

**Issue by paemason** [GoogleCloudPlatform/bank-of-anthos#87]
I was able to deploy this on my on-prem cluster with some simple modifications.

1) I created a namespace (`kubectl create ns bank-of-anthos`) to make it simple to clean up after, as on-prem clusters aren't quite as easy to build and tear down  as gke in the cloud. I then modified the create secret and apply commands to include `-n bank-of-anthos` when running them. This is optional but probably a best practice.

2) I modified ./kubernetes-manifests/frontend.yaml to include a `loadBalancerIP` field which is required when exposing services on prem. So my service definition looks like follows:
```
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  loadBalancerIP: <enter available VIP here>
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
```
